# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{BackupMan}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Markus Strauss"]
  s.date = %q{2010-09-01}
  s.default_executable = %q{backup_man}
  s.description = %q{A tool for system administrators to easily configure pull-over-SSH backups. Install this gem on your backup server. Configure your backups definitions in /etc/backup_man and run backup_man from cron to securely pull your data over SSH.}
  s.email = %q{Markus@ITstrauss.eu}
  s.executables = ["backup_man"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardopts",
     "BackupMan.gemspec",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/backup_man",
     "examples/example-host-config",
     "features/development.feature",
     "features/dsl_parameters.feature",
     "features/logfile.feature",
     "features/overview.feature",
     "features/step_definitions/common_steps.rb",
     "features/step_definitions/dsl_parameters_steps.rb",
     "features/step_definitions/logfile_steps.rb",
     "features/support/common.rb",
     "features/support/env.rb",
     "features/support/matchers.rb",
     "lib/backup_man.rb",
     "lib/backup_man/backup.rb",
     "lib/backup_man/backup_man.rb",
     "lib/backup_man/cli.rb",
     "lib/backup_man/command.rb",
     "lib/backup_man/dsl.rb",
     "lib/backup_man/log.rb",
     "lib/backup_man/mysql.rb",
     "lib/backup_man/rsync.rb",
     "lib/backup_man/tar.rb",
     "spec/BackupMan_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/oowoo/BackupMan}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{backupman}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A tool for system administrators to easily configure pull-over-SSH backups.}
  s.test_files = [
    "spec/BackupMan_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0.4.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.4.4"])
      s.add_runtime_dependency(%q<log4r>, [">= 1.1.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0.4.0"])
      s.add_dependency(%q<cucumber>, [">= 0.4.4"])
      s.add_dependency(%q<log4r>, [">= 1.1.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0.4.0"])
    s.add_dependency(%q<cucumber>, [">= 0.4.4"])
    s.add_dependency(%q<log4r>, [">= 1.1.2"])
  end
end

